### ISSUE TITLE
Could you please provide some documents or explanation of codes?

### ISSUE THREAD

**Issue by WilliamWangPeng** [turrentrock/Ray-Tracing#1]
Hi dear author,  
    It's a great honor to open one issue here, truly honor.  I just begin to learn computer graphics and have compiled your program successfully, but it is hard for me to read the codes, could you please provide some explanation or PPT or papers about the code to me?   👍 

thank you  
Best Regards with kindness  
William

**Comment by satyatejachikatla** [comment]
Hi William,

This repo is a tutorial followed from blog post https://devblogs.nvidia.com/accelerated-ray-tracing-cuda/
The above blog has step-by-step reasoning of the code , also for further details you can walk through the commit history.

For details, on the math, you can look at blog post https://raytracing.github.io/books/RayTracingInOneWeekend.html#overview

If you are new to the world of GP-GPU you can go through the video series: https://nptel.ac.in/courses/106105220/

Regards,
C Satya Teja

**Comment by WilliamWangPeng** [comment]
> Hi William,
> 
> This repo is a tutorial followed from blog post https://devblogs.nvidia.com/accelerated-ray-tracing-cuda/
> The above blog has step-by-step reasoning of the code , also for further details you can walk through the commit history.
> 
> For details, on the math, you can look at blog post https://raytracing.github.io/books/RayTracingInOneWeekend.html#overview
> 
> If you are new to the world of GP-GPU you can go through the video series: https://nptel.ac.in/courses/106105220/
> 
> Regards,
> C Satya Teja

thank you dear @turrentrock     
    It's very nice of you, 🥇   :-)
    I will try to read the codes following the main document you have given me,  It's such a gift in the Teachers' Day 👍   

thank you  
best regards  
William
